export const jadwal = [
  {
    id: 1,
    day: "Senin",
    time: "08:00 - 10:00",
    subject: "Praktikum Pemrograman Berbasis Web",
    code: "IF2340042",
    lecturer: "Rima Dias Ramadhani, S.Kom., M.Kom",
    location: "Ruang: A101, Gedung GKB 2 (Gedung A)",
  },
    {
        id: 2,
        day: "Senin",
        time: "13:00 - 15:00",
        subject: "Algoritma dan Pemrograman",
        code: "IF2340050",
        lecturer: "Budi Santoso, S.T., M.T.",
        location: "Ruang: B202, Gedung GKB 1 (Gedung B)",
    },
    {
        id: 3,
        day: "Rabu",
        time: "13:00 - 15:00",
        subject: "Basis Data",
        code: "IF2340060",
        lecturer: "Siti Aminah, S.Kom., M.Kom",
        location: "Ruang: C303, Gedung GKB 3 (Gedung C)",
    },
    {
        id: 4,
        day: "Rabu",
        time: "08:00 - 10:00",
        subject: "Jaringan Komputer",
        code: "IF2340070",
        lecturer: "Ahmad Zaki, S.Kom., M.Kom",
        location: "Ruang: D404, Gedung GKB 4 (Gedung D)",
    },
    {
        id: 5,
        day: "Rabu",
        time: "10:00 - 12:00",
        subject: "Praktikum Jaringan Komputer",
        code: "IF2340070",
        lecturer: "Ahmad Zaki, S.Kom., M.Kom ",
        location: "Ruang: D404, Gedung GKB 4 (Gedung D)",
    },
    {
        id: 6,
        day: "Rabu",
        time: "13:00 - 15:00",
        subject: "Rekayasa Perangkat Lunak",
        code: "IF2340080",
        lecturer: "Dewi Sartika, S.Kom., M.Kom",
        location: "Ruang: E505, Gedung GKB 5 (Gedung E)",
    },
    {
        id: 7,
        day: "Kamis",
        time: "10:00 - 12:00",
        subject: "Pengolahan Citra Digital",
        code: "IF2340070",
        lecturer: "Ahmad Zaki, S.Kom., M.Kom",
        location: "Ruang: D404, Gedung GKB 4 (Gedung D)",
    },
    {
        id: 8,
        day: "Kamis",
        time: "13:00 - 14:40",
        subject: "Praktikum Pengolahan Citra Digital",
        code: "IF2340070",
        lecturer: "Ahmad Zaki, S.Kom., M.Kom",
        location: "Ruang: D404, Gedung GKB 4 (Gedung D)",
    }

];
