export const jadwal = [
  {
    id: 1,
    day: "Senin",
    time: "08:00 - 10:00",
    subject: "Praktikum Pemrograman Berbasis Web",
    code: "IF2340042",
    lecturer: "Rima Dias Ramadhani, S.Kom., M.Kom",
    location: "Ruang: A101, Gedung GKB 2 (Gedung A)",
  },
  {
    id: 2,
    day: "Senin",
    time: "13:00 - 15:00",
    subject: "Algoritma dan Pemrograman",
    code: "IF2340050",
    lecturer: "Budi Santoso, S.T., M.T.",
    location: "Ruang: B202, Gedung GKB 1 (Gedung B)",
  },
  {
    id: 3,
    day: "Rabu",
    time: "13:00 - 15:00",
    subject: "Basis Data",
    code: "IF2340060",
    lecturer: "Siti Aminah, S.Kom., M.Kom",
    location: "Ruang: C303, Gedung GKB 3 (Gedung C)",
  },
  {
    id: 4,
    day: "Rabu",
    time: "08:00 - 10:00",
    subject: "Jaringan Komputer",
    code: "IF2340070",
    lecturer: "Ahmad Zaki, S.Kom., M.Kom",
    location: "Ruang: D404, Gedung GKB 4 (Gedung D)",
  },
  {
    id: 5,
    day: "Rabu",
    time: "10:00 - 12:00",
    subject: "Praktikum Jaringan Komputer",
    code: "IF2340070",
    lecturer: "Ahmad Zaki, S.Kom., M.Kom ",
    location: "Ruang: D404, Gedung GKB 4 (Gedung D)",
  },
  {
    id: 6,
    day: "Rabu",
    time: "13:00 - 15:00",
    subject: "Rekayasa Perangkat Lunak",
    code: "IF2340080",
    lecturer: "Dewi Sartika, S.Kom., M.Kom",
    location: "Ruang: E505, Gedung GKB 5 (Gedung E)",
  },
  {
    id: 7,
    day: "Kamis",
    time: "10:00 - 12:00",
    subject: "Pengolahan Citra Digital",
    code: "IF2340070",
    lecturer: "Ahmad Zaki, S.Kom., M.Kom",
    location: "Ruang: D404, Gedung GKB 4 (Gedung D)",
  },
  {
    id: 8,
    day: "Kamis",
    time: "13:00 - 14:40",
    subject: "Praktikum Pengolahan Citra Digital",
    code: "IF2340070",
    lecturer: "Ahmad Zaki, S.Kom., M.Kom",
    location: "Ruang: D404, Gedung GKB 4 (Gedung D)",
  },
];

export const pembayaran = [
  {
    id: 1,
    semester: "2025/2026 Gasal",
    period: "1 Aug. 2025 - 31 Jan. 2026",
    totalAmount: 40000000,
    details: [
      {
        name: "Biaya Kuliah",
        amount: 2000000,
      },
      {
        name: "Praktek",
        amount: 375000,
      },
      {
        name: "Internet",
        amount: 100000,
      },
      {
        name: "Registrasi",
        amount: 30000,
      },
      {
        name: "Asuransi",
        amount: 20000,
      },
      {
        name: "KP/PBL",
        amount: 375000,
      },
    ],
    note: "Pembayaran melalui kode Pembayaran yang tertera di BSI atau ATM dengan kode pembayaran yang ada.",
  },
  {
    id: 2,
    semester: "2024/2025 Genap",
    period: "1 Feb. 2025 - 31 Jul. 2025",
    totalAmount: 3900000,
    details: [
      {
        name: "Biaya Kuliah",
        amount: 2000000,
      },
      {
        name: "Praktek",
        amount: 350000,
      },
      {
        name: "Internet",
        amount: 100000,
      },
      {
        name: "Registrasi",
        amount: 30000,
      },
      {
        name: "Asuransi",
        amount: 20000,
      },
      {
        name: "KP/PBL",
        amount: 300000,
      },
    ],
    note: "Pembayaran telah lunas pada tanggal 5 Feb. 2025",
  },
];

export const PembayaranBankBSI = [
  {
    id: 1,
    method: "Via Teller",
    steps: [
      "Isi slip yang sudah disediakan ",
      "Setelah transaksi berhasil di proses, simpan slip dan cek status tagihan terbayar di siamus.",
    ],
  },
  {
    id: 2,
    method: "Via ATM",
    steps: [
      "Masukkan kartu ATM",
      "Pilih menu pembayaran/pembelian, kemudian pilih menu akademik",
      "Masukkan kode: ",
      "Pastikan nama dan tagihan yang muncul sudah sesuai, pilih benar, transaksi berhasil",
      "Simpan bukti pembayaran dan cek status tagihan terbayar di siamus",
    ],
  },
  {
    id: 3,
    method: "Via Mobile Banking BSI/BYOND",
    steps: [
      "Pilih menu bayar, kemudian pilih akademik",
      "Pilih no rekening apabila rekening lebih dari satu",
      "Masukkan nama akademik 9005 (Universitas Muhammadiyah Semarang/UNMUH Semarang)",
      "Pastikan nama dan tagihan yang muncul sudah sesuai, pilih benar, transaksi berhasil",
      "Masukkan kode 0323023012, dan dilanjutkan pengisian PIN",
      "Pastikan nama mahasiswa dan jumlah tagihan sudah sesuai",
      "Pilih selanjutnya, transaksi berhasil",
      "Simpan bukti pembayaran dan cek status tagihan terbayar di siamus",
    ],
  },
  {
    id: 4,
    method: "Via ATM Bank Lain",
    steps: [
      "Pilih menu transfer bank lain",
      "Masukkan no Rekening 45190090050323023012",
      "Masukkan kode: ",
      "Masukkan nominal transfer yang sesuai dengan tagihan di siamus, jika nominal yang diinput tidak sesuai maka transaksi gagal",
      "Menu konfirmasi muncul, cek kembali nama rekening tujuan dan nominal tagihan",
      "Pilih benar apabila nama dan tagihan yang muncul sudah sesuai, transaksi berhasil",
      "Simpan bukti pembayaran dan cek status tagihan terbayar di siamus",
    ],
  },
  {
    id: 5,
    method: "Via Mobile Banking Bank Lain",
    steps: [
      "Pilih menu transfer bank lain",
      "Pilih Bank BSI (Bank Syariah Indonesia)",
      "Masukkan no Rekening 45190090050323023012",
      "Masukkan nominal transfer yang sesuai dengan tagihan di siamus, jika nominal yang diinput tidak sesuai maka transaksi gagal",
      "Pastikan layanan transfer yang dipilih adalah layanan online (biaya transfer 6.500)",
      "Masukkan PIN, transaksi berhasil",
      "Simpan bukti pembayaran dan cek status tagihan terbayar di siamus",
    ],
  },
];

export const PembayaranBankJatengSyariah = [
  {
    id: 1,
    method: "Via Teller",
    steps: [
      "Isi slip yang sudah disediakan ",
      "Setelah transaksi berhasil di proses, simpan slip dan cek status tagihan terbayar di siamus.",
    ],
  },
  {
    id: 2,
    method: "Via ATM Bank Jateng Syariah",
    steps: [
      "Pilih menu pembayaran/pembelian, kemudian pilih menu universitas",
      "Masukkan ID Universitas 042",
      "Masukkan kode pembayaran: ",
      "Pastikan nama dan tagihan yang muncul sudah sesuai",
      "Pilih bayar semua tagihan, klik benar, transaksi berhasil",
      "Simpan bukti pembayaran dan cek status tagihan terbayar di siamus",
    ],
  },
  {
    id: 3,
    method: "Via Mobile Banking BSI/BYOND",
    steps: [
      "Pilih menu bayar, kemudian pilih akademik",
      "Pilih no rekening apabila rekening lebih dari satu",
      "Masukkan nama akademik 9005 (Universitas Muhammadiyah Semarang/UNMUH Semarang)",
      "Pastikan nama dan tagihan yang muncul sudah sesuai, pilih benar, transaksi berhasil",
      "Masukkan kode 0323023012, dan dilanjutkan pengisian PIN",
      "Pastikan nama mahasiswa dan jumlah tagihan sudah sesuai",
      "Pilih selanjutnya, transaksi berhasil",
      "Simpan bukti pembayaran dan cek status tagihan terbayar di siamus",
    ],
  },
  {
    id: 4,
    method: "Via ATM Bank Lain",
    steps: [
      "Pilih menu transfer bank lain",
      "Masukkan no Rekening 45190090050323023012",
      "Masukkan kode: ",
      "Masukkan nominal transfer yang sesuai dengan tagihan di siamus, jika nominal yang diinput tidak sesuai maka transaksi gagal",
      "Menu konfirmasi muncul, cek kembali nama rekening tujuan dan nominal tagihan",
      "Pilih benar apabila nama dan tagihan yang muncul sudah sesuai, transaksi berhasil",
      "Simpan bukti pembayaran dan cek status tagihan terbayar di siamus",
    ],
  },
  {
    id: 5,
    method: "Via Mobile Banking Bank Lain",
    steps: [
      "Pilih menu transfer bank lain",
      "Pilih Bank BSI (Bank Syariah Indonesia)",
      "Masukkan no Rekening 45190090050323023012",
      "Masukkan nominal transfer yang sesuai dengan tagihan di siamus, jika nominal yang diinput tidak sesuai maka transaksi gagal",
      "Pastikan layanan transfer yang dipilih adalah layanan online (biaya transfer 6.500)",
      "Masukkan PIN, transaksi berhasil",
      "Simpan bukti pembayaran dan cek status tagihan terbayar di siamus",
    ],
  },
];

export const studentresultdata = {
  khs2026_2027_ganjil: [
    {
      id: 1,
      subject: "Basis Data",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 61,
      tugas: 60,
      score: 45.5,
      grade: "DE",
      sks: 1,
    },
    {
      id: 2,
      subject: "Rekayasa Perangkat Lunak",
      code: "IF2340080",
      lecturer: "Dewi Sartika, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 80,
      grade: "CD",
      sks: 1,
    },
    {
      id: 3,
      subject: "Praktikum Pemrograman Berbasis Web",
      code: "IF2340042",
      lecturer: "Rima Dias Ramadhani, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 85,
      grade: "A",
      sks: 4,
    },
    {
      id: 4,
      subject: "Algoritma dan Pemrograman",
      code: "IF2340050",
      lecturer: "Budi Santoso, S.T., M.T.",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 78,
      grade: "AB",
      sks: 3,
    },
    {
      id: 5,
      subject: "Basis Data",
      code: "IF2340060",
      lecturer: "Siti Aminah, S.Kom., M.Kom",
      uts: 90,
      uas: 35,
      tugas: 40,
      score: 60,
      grade: "E",
      sks: 1,
    },
  ],
  khs2025_2026_genap: [
    {
      id: 1,
      subject: "Jaringan Komputer",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 88,
      grade: "A",
      sks: 3,
    },
    {
      id: 2,
      subject: "Rekayasa Perangkat Lunak",
      code: "IF2340080",
      lecturer: "Dewi Sartika, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 80,
      grade: "B",
      sks: 3,
    },
    {
      id: 3,
      subject: "Praktikum Pemrograman Berbasis Web",
      code: "IF2340042",
      lecturer: "Rima Dias Ramadhani, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 85,
      grade: "A",
      sks: 3,
    },
    {
      id: 4,
      subject: "Algoritma dan Pemrograman",
      code: "IF2340050",
      lecturer: "Budi Santoso, S.T., M.T.",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 78,
      grade: "AB",
      sks: 3,
    },
    {
      id: 5,
      subject: "Basis Data",
      code: "IF2340060",
      lecturer: "Siti Aminah, S.Kom., M.Kom",
      uts: 90,
      uas: 95,
      tugas: 85,
      score: 92,
      grade: "A",
      sks: 3,
    },
  ],

  khs2025_2026_ganjil: [
    {
      id: 1,
      subject: "Jaringan Komputer",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 88,
      grade: "AB",
      sks: 2,
    },
    {
      id: 2,
      subject: "Rekayasa Perangkat Lunak",
      code: "IF2340080",
      lecturer: "Dewi Sartika, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 80,
      grade: "B",
      sks: 2,
    },
    {
      id: 3,
      subject: "Rekayasa Perangkat Lunak",
      code: "IF2340080",
      lecturer: "Dewi Sartika, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 80,
      grade: "BC",
      sks: 1,
    },
    {
      id: 4,
      subject: "Rekayasa Perangkat Lunak",
      code: "IF2340080",
      lecturer: "Dewi Sartika, S.Kom., M.Kom",
      uts: 50,
      uas: 70,
      tugas: 62,
      score: 60,
      grade: "BC",
      sks: 4,
    },
    {
      id: 5,
      subject: "Praktikum Pemrograman Berbasis Web",
      code: "IF2340042",
      lecturer: "Rima Dias Ramadhani, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 85,
      grade: "A",
      sks: 2,
    },
    {
      id: 6,
      subject: "Algoritma dan Pemrograman",
      code: "IF2340050",
      lecturer: "Budi Santoso, S.T., M.T.",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 78,
      grade: "AB",
      sks: 2,
    },
    {
      id: 7,
      subject: "Basis Data",
      code: "IF2340060",
      lecturer: "Siti Aminah, S.Kom., M.Kom",
      uts: 90,
      uas: 95,
      tugas: 85,
      score: 92,
      grade: "CD",
      sks: 3,
    },
  ],

  khs2024_2025_genap: [
    {
      id: 1,
      subject: "Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 80,
      grade: "BC",
      sks: 3,
    },
    {
      id: 2,
      subject: "Praktikum Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 88,
      grade: "AB",
      sks: 3,
    },
    {
      id: 3,
      subject: "Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 80,
      grade: "B",
      sks: 4,
    },
    {
      id: 4,
      subject: "Praktikum Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 88,
      grade: "A",
      sks: 3,
    },
    {
      id: 5,
      subject: "Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 80,
      grade: "B",
      sks: 1,
    },
    {
      id: 6,
      subject: "Praktikum Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 88,
      grade: "A",
      sks: 2,
    },
  ],

  khs2024_2025_ganjil: [
    {
      id: 1,
      subject: "Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 80,
      grade: "A",
      sks: 2,
    },
    {
      id: 2,
      subject: "Praktikum Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 88,
      grade: "AB",
      sks: 3,
    },
    {
      id: 3,
      subject: "Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 70.9,
      grade: "B",
      sks: 4,
    },
    {
      id: 4,
      subject: "Praktikum Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 70.5,
      grade: "A",
      sks: 3,
    },
    {
      id: 5,
      subject: "Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 68.3,
      grade: "B",
      sks: 1,
    },
    {
      id: 6,
      subject: "Praktikum Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 98.1,
      grade: "A",
      sks: 2,
    },
  ],

  khs2023_2024_genap: [
    {
      id: 1,
      subject: "Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 80,
      grade: "BC",
      sks: 3,
    },
    {
      id: 2,
      subject: "Praktikum Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 88,
      grade: "AB",
      sks: 2,
    },
    {
      id: 3,
      subject: "Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 80,
      uas: 85,
      tugas: 75,
      score: 80,
      grade: "B",
      sks: 4,
    },
    {
      id: 4,
      subject: "Praktikum Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 40,
      uas: 55,
      tugas: 80,
      score: 55.3,
      grade: "E",
      sks: 1,
    },
    {
      id: 5,
      subject: "Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 41,
      uas: 85,
      tugas: 75,
      score: 77.9,
      grade: "C",
      sks: 1,
    },
    {
      id: 6,
      subject: "Praktikum Pengolahan Citra Digital",
      code: "IF2340070",
      lecturer: "Ahmad Zaki, S.Kom., M.Kom",
      uts: 85,
      uas: 90,
      tugas: 80,
      score: 88,
      grade: "A",
      sks: 2,
    },
  ],
  khs2023_2024_ganjil: [],
};

export const KALENDERAKADEMIK = {
  Gasal_2025_2026: [
    {
      id: 1,
      kegiatan: "	Penerimaan Mahasiswa Baru (Reguler)",
      waktu: "Desember 2024 s/d Agustus 2025",
    },
    {
      id: 2,
      kegiatan: "Penerimaan Mahasiswa Baru (pindahan)",
      waktu: "Juli s/d Agustus 2025",
    },
    {
      id: 3,
      kegiatan: "Testing Calon Mahasiswa",
      waktu: "Di Selenggarakan Setiap Hari",
    },
    {
      id: 4,
      kegiatan: "Pengumuman Penerimaan",
      waktu: "Di Selenggarakan Setiap Hari",
    },
    {
      id: 5,
      kegiatan: "Registrasi Mahasiswa Baru (reguler)",
      waktu: "Setiap hari s/d 30 Agustus 2025",
    },
    {
      id: 6,
      kegiatan: "Registrasi Mahasiswa Baru (pindahan)",
      waktu: "Juli s/d September 2025",
    },
    {
      id: 7,
      kegiatan: "Masa Ta’aruf Universitas",
      waktu: "08 s/d 10 September 2025",
    },
    {
      id: 8,
      kegiatan: "Studium General",
      waktu: "11 September 2025 s/d 30 Januari 2026",
    },
    {
      id: 9,
      kegiatan: "Masa Ta’aruf Fakultas",
      waktu: "11 s/d 13 September 2025",
    },
    {
      id: 10,
      kegiatan: "Registrasi Mahasiswa dan Bimbingan Dosen Wali",
      waktu: "1 Agustus s/d 04 September 2025",
    },
    {
    id: 12,
    kegiatan: "Masa Pengajuan Aktif Kembali",
    waktu: "4 – 15 Agustus 2025",
  },
  {
    id: 13,
    kegiatan: "Laporan Lulusan ke LL DIKTI Wisuda ke-47",
    waktu: "14 Oktober 2025",
  },
  {
    id: 14,
    kegiatan: "Penyelenggaraan Wisuda ke-47",
    waktu: "28 Oktober 2025",
  },
  {
    id: 15,
    kegiatan: "Laporan Pendidikan ke Feeder PD Dikti - Tahap 2 : Semester Genap 2024/2025",
    waktu: "15 Oktober 2025",
  },
  {
    id: 16,
    kegiatan: "Laporan Pendidikan ke Feeder PD Dikti - Tahap 1 : Semester Gasal 2025/2026",
    waktu: "30 Oktober 2025",
  },
  {
    id: 17,
    kegiatan: "Verifikasi berkas Mahasiswa Peserta MBKM pada akun SIAMUS UNIMUS",
    waktu: "02 September s/d 11 Oktober 2025",
  },
  {
    id: 18,
    kegiatan: "Awal dan Akhir Perkuliahan",
    waktu: "15 September 2025 s/d 02 Januari 2026",
  },
  {
    id: 19,
    kegiatan: "Ujian Tengah Semester (UTS)",
    waktu: "27 – 31 Oktober 2025",
  },
  {
    id: 20,
    kegiatan: "Monitoring dan Evaluasi MBKM Tengah semester",
    waktu: "01 s/d 08 November 2025",
  },
  {
    id: 21,
    kegiatan: "Pekan Teduh",
    waktu: "05 s/d 09 Januari 2026",
  },
  {
    id: 22,
    kegiatan: "Monitoring dan Evaluasi MBKM Akhir semester",
    waktu: "01 s/d 05 Januari 2026",
  },
  {
    id: 23,
    kegiatan: "Ujian Akhir Semester (UAS)",
    waktu: "12 s/d 23 Januari 2026",
  },
  {
    id: 24,
    kegiatan: "Laporan akhir dan penilaian program MBKM oleh PIC",
    waktu: "14 s/d 15 Januari 2026",
  },
  {
    id: 25,
    kegiatan: "Yudisium Akhir Semester",
    waktu: "28 Pebruari 2026",
  },
  {
    id: 26,
    kegiatan: "9. Konversi nilai dan pelaporan kegiatan MBKM oleh Program Studi",
    waktu: "16 Januari s/d 21 Februari 2026",
  },
  {
    id: 27,
    kegiatan: "Kuliah Sisipan Semester Gasal 2025/2026",
    waktu: "02 s/d 13 Februari 2026",
  },
  {
    id: 28,
    kegiatan: "Upgrading kegiatan MBKM",
    waktu: "12 s/d 19 Februari 2026",
  },
  {
    id: 29,
    kegiatan: "Kuliah Kerja Nyata (KKN)",
    waktu: "Februari 2026",
  },
  {
    id: 30,
    kegiatan: "Laporan Lulusan ke LLDIKTI Wisuda ke-48",
    waktu: "10 Februari 2026",
  },
  {
    id: 31,
    kegiatan: "Penyelenggaraan Wisuda ke-48",
    waktu: "24 Februari 2026",
  },
  {
    id: 32,
    kegiatan: "Penyusunan Laporan Pendidikan Semester Gasal 2025/2026 Tingkat Program Studi Aktifitas Kegiatan Mengajar (AKM) oleh Program Studi",
    waktu: "Februari s/d Maret 2026",
  },
  {
    id: 33,
    kegiatan: "Pengiriman Laporan Akademik Kegiatan MBKM oleh Program Studi dan PIC MBKM ke LP3M",
    waktu: "27 Februari 2026",
  },
  {
    id: 34,
    kegiatan: "Pengiriman Laporan Pendidikan oleh Program Studi ke Universitas",
    waktu: "10 April 2026",
  }
  ],

  Genap_2025_2026: [
    {
      id: 1,
      kegiatan: "Penerimaan Mahasiswa Baru (pindahan, dan profesi)",
      waktu: "Januari s/d Maret 2025",
    },
    {
      id: 2,
      kegiatan: "Registrasi Mahasiswa Baru (pindahan)",
      waktu: "Januari s/d Maret 2025",
    },
    {
      id: 3,
      kegiatan: "Herregistrasi Mahasiswa dan Bimbingan Dosen Wali",
      waktu: "02 Februari s/d 06 Maret 2026",
    },
    {
      id: 4,
      kegiatan: "Masa Pengajuan Cuti",
      waktu: "26 Januari s/d 07 Pebruari 2025",
    },
    {
      id: 5,
      kegiatan: "Masa Pengajuan Aktif Kembali",
      waktu: "26 Januari s/d 07 Pebruari 2025",
    },
    {
      id: 6,
      kegiatan: "Laporan Tahap 2: Laporan Pendidikan Semester Gasal 2025/2026 ke Feeder PD Dikti Aktifitas Kegiatan Mengajar (AKM)",
      waktu: "16 April 2026",
    },
    {
      id: 7,
      kegiatan: "Verifikasi berkas peserta MBKM",
      waktu: "02 Februari s/d 06 Maret 2026",
    },
    {
      id: 8,
      kegiatan: "Libur Idul Fitri 1447 H",
      waktu: "16 – 25 Maret 2026",
    },
    {
      id: 9,
      kegiatan: "Laporan Lulusan ke LLDIKTI Wisuda ke-49",
      waktu: "16 Juni 2026",
    },
    {
      id: 10,
      kegiatan: "Penyelenggaraan Wisuda ke-49",
      waktu: "30 Juni 2026",
    },
    {
      id: 11,
      kegiatan: "Awal dan Akhir Perkuliahan",
      waktu: "09 Maret s/d 03 Juli 2026",
    },
    {
      id: 12,
      kegiatan: "Monitoring dan Evaluasi MBKM Tengah Semester",
      waktu: "09 s/d 11 Mei 2026",
    },
    {
      id: 13,
      kegiatan: "Ujian Tengah Semester",
      waktu: "20 s/d 24 April 2026",
    },
    {
      id: 14,
      kegiatan: "Pekan Teduh",
      waktu: "06 s/d 10 Juli 2026",
    },
    {
      id: 15,
      kegiatan: "Ujian Akhir Semester",
      waktu: "13 s/d 24 Juli 2026",
    },
    {
      id: 16,
      kegiatan: "Monitoring dan Evaluasi MBKM Akhir Semester",
      waktu: "16 s/d 20 Juli 2026",
    },
    {
      id: 17,
      kegiatan: "Yudisium Akhir Semester",
      waktu: "07 Agustus 2026",
    },
    {
      id: 18,
      kegiatan: "Laporan akhir dan penilaian program MBKM oleh PIC",
      waktu: "16 s/d 19 Juli 2026",
    },
    {
      id: 19,
      kegiatan: "Konversi nilai dan pelaporan kegiatan MBKM oleh Program Studi",
      waktu: "23 s/d 27 Juli 2026",
    },
    {
      id: 20,
      kegiatan: "Kuliah Sisipan Semester Genap 2025/2026",
      waktu: "10 s/d 21 Agustus 2026",
    },
    {
      id: 21,
      kegiatan: "AMAI Program Studi",
      waktu: "Mei 2026",
    },
    {
      id: 22,
      kegiatan: "AMNAI Unit",
      waktu: "Juni 2026",
    },
    {
      id: 23,
      kegiatan: "Kuliah Kerja Nyata (KKN)",
      waktu: "Agustus 2026",
    },
    {
      id: 24,
      kegiatan: "Penyusunan Laporan Pendidikan Semester Genap 2025/2026 Tingkat Program Studi Aktifitas Kegiatan Mengajar (AKM) oleh Program Studi",
      waktu: "Agustus s/d September 2026",
    },
    {
      id: 25,
      kegiatan: "Pengiriman Laporan Akademik Kegiatan MBKM oleh Program Studi dan PIC MBKM ke LP3M",
      waktu: "28 Agustus 2026",
    },
    {
      id: 26,
      kegiatan: "Pengiriman Laporan Pendidikan oleh Program Studi ke Universitas",
      waktu: "02 Oktober 2026",
    }
  ],
};

